### ISSUE TITLE
Delete an element in circular linked list

### ISSUE THREAD

**Issue by amritansh22** [amritansh22/Data-Structures-and-Algorithms-in-cpp#73] opened 2020-09-27 12:24 UTC

**Comment by sukritidawar** [comment] 2020-09-27 13:29
I want to work on this issue in cpp

**Comment by amritansh22** [comment] 2020-09-27 13:44
@sukritidawar Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

**Comment by ankitksh81** [comment] 2020-09-27 19:11
Hi, @amritansh22 Can I work on this issue ?

**Comment by sukritidawar** [comment] 2020-09-28 05:47
> @sukritidawar Yes you may start working on this issue, make sure to follow all the points mentioned in contribution guide and make a PR once done.

Hey, once it was assigned to me, I was working on this, and was about to make a pr...but since someone else submitted the pr, you closed this issue...it shouldn't be like this I think, if this would be the case, then there won't be the need to comment also...right? I mean why did you even assign me the issue in the first place also?

**Comment by ankitksh81** [comment] 2020-09-28 05:54
Hi @sukritidawar, He didn't assign you this issue. He said you can go ahead and do it. Since there was no one assigned on this issue that's why I also did it. It doesn't mean that you cannot create a PR, go ahead and please do it. I saw you commented on multiple issues, so I thought you won't mind if I do anyone since it is my first time also.

**Comment by ankitksh81** [comment] 2020-09-28 05:56
@sukritidawar One more thing, He didn't close the issue, if you look carefully the issue is still open. I was the one who closed the PR because it won't be counted for Hacktoberfest if done before 1st oct.

**Comment by sukritidawar** [comment] 2020-09-28 06:07
> Hi @sukritidawar, He didn't assign you this issue. He said you can go ahead and do it. Since there was no one assigned on this issue that's why I also did it. It doesn't mean that you cannot create a PR, go ahead and please do it. I saw you commented on multiple issues, so I thought you won't mind if I do anyone since it is my first time also.

Well, if I had commented on the issue first, and the author had written that yes I can go ahead with it, I think that you should've considered this in account....Regarding the prs, if you and I are working on the same issue and in the same language, then I think that only one pr would be merged, right?

**Comment by amritansh22** [comment] 2020-09-28 06:09
@sukritidawar First of all apologies. Secondly, try to understand the situation here generally we assigning issues to someone, then they make a PR. But here when I assign an issue to someone they completely vanish and the issue becomes stale. So to avoid this I stopped assigning issues. Now in this also I thought that would be no longer interested, s I merged @ankitksh81 PR.

**Comment by amritansh22** [comment] 2020-09-28 06:10
@sukritidawar What you can do to avoid further problems is to make your own issues.

**Comment by ankitksh81** [comment] 2020-09-28 06:10
@amritansh22 did you merged my PR ?
But I closed it right?

**Comment by ankitksh81** [comment] 2020-09-28 06:12
> @sukritidawar First of all apologies. Secondly, try to understand the situation here generally we assigning issues to someone, then they make a PR. But here when I assign an issue to someone they completely vanish and the issue becomes stale. So to avoid this I stopped assigning issues. Now in this also I thought that would be no longer interested, s I merged @ankitksh81 PR.

She had two issues, If she doesn't want to give chance to others then it's alright she can go ahead and do it.

**Comment by amritansh22** [comment] 2020-09-28 06:13
@ankitksh81 No your PR isn't merged because you yourself closed it, that's why this issue is still open

**Comment by sukritidawar** [comment] 2020-09-28 06:13
> @sukritidawar First of all apologies. Secondly, try to understand the situation here generally we assigning issues to someone, then they make a PR. But here when I assign an issue to someone they completely vanish and the issue becomes stale. So to avoid this I stopped assigning issues. Now in this also I thought that would be no longer interested, s I merged @ankitksh81 PR.
I understand that completely, but I think that not everyone vanishes after being assigned, and since you had labelled hacktober fest, so I was also waiting for October 1st to make a pr....Just a suggestion, please assign the issue from next time to avoid any confusions and misconceptions, since two of my issues were closed like this only.Thanks.

**Comment by amritansh22** [comment] 2020-09-28 06:14
![image](https://user-images.githubusercontent.com/29978031/94396627-ef2b5180-017f-11eb-8251-1efca7a52365.png)
See this issue: He asked me assign and 3 days have passed
https://github.com/amritansh22/Data-Structures-and-Algorithms-in-cpp/issues/17

**Comment by amritansh22** [comment] 2020-09-28 06:16
@sukritidawar Since you want to take part in Octoberbest. I would recommend you to open 5 issues now and assign them to you. On 1st October you may create a PR for all of them.

**Comment by sukritidawar** [comment] 2020-09-28 06:18
> > @sukritidawar First of all apologies. Secondly, try to understand the situation here generally we assigning issues to someone, then they make a PR. But here when I assign an issue to someone they completely vanish and the issue becomes stale. So to avoid this I stopped assigning issues. Now in this also I thought that would be no longer interested, s I merged @ankitksh81 PR.
> 
> She commented on two issues, If she doesn't want to give chance to others then it's alright she can go ahead and do it.

See, to be very clear, I don't have any problem with you working on the issue. Please go ahead and work on it. I never said that I don't want to give a chance to others. I was just saying so that there won't be any confusion and misconceptions in the future. I'm sorry if you felt that I didn't want to give others a chance, but generally on github I've seen all this happening very smoothly, and this was the first time I had seen something like this, so I thought to clear the doubts.

**Comment by ankitksh81** [comment] 2020-09-28 06:19
@amritansh22 it's upto you, you can assign the issue to who ever you want. I'm just saying that she already have an issue which she doing. But if she want's to do both then I don't have a problem.

**Comment by ankitksh81** [comment] 2020-09-28 06:22
> > > @sukritidawar First of all apologies. Secondly, try to understand the situation here generally we assigning issues to someone, then they make a PR. But here when I assign an issue to someone they completely vanish and the issue becomes stale. So to avoid this I stopped assigning issues. Now in this also I thought that would be no longer interested, s I merged @ankitksh81 PR.
> > 
> > 
> > She commented on two issues, If she doesn't want to give chance to others then it's alright she can go ahead and do it.
> 
> See, to be very clear, I don't have any problem with you working on the issue. Please go ahead and work on it. I never said that I don't want to give a chance to others. I was just saying so that there won't be any confusion and misconceptions in the future. I'm sorry if you felt that I didn't want to give others a chance, but generally on github I've seen all this happening very smoothly, and this was the first time I had seen something like this, so I thought to clear the doubts.

yeah same for me, it's my first time so since I saw no one assigned that's why I did it. I coded it for more than 2 hrs last night. I hope you understand. But again you can work on it. I don't mind. I will create a new issue and do that as @amritansh22 suggested.

**Comment by amritansh22** [comment] 2020-09-28 06:25
@ankitksh81 @sukritidawar Apologies to both of you. To avoid this problem to others, from now forth I would assign every issue someone. Now I am going to create few issues, you may to work upon them and I would assign them to you.

**Comment by piyush9311** [comment] 2020-09-28 15:53
May  I work on this issue

**Comment by ankitksh81** [comment] 2020-09-28 16:14
@piyush9311, already working on it. Sorry.

**Closed** 2020-11-05 13:11 UTC
Labels: Hacktoberfest, Hacktoberfest2020, good first issue
