### ISSUE TITLE
Multiplication w/o using multiplication operator.

### ISSUE THREAD

**Issue by Rajdeep-G** [amritansh22/Data-Structures-and-Algorithms-in-cpp#230] opened 2020-10-01 06:31 UTC
I will write a code with full documentation about how to find the product of two numbers without using the multiplication (*) operation.

**Comment by amritansh22** [comment] 2020-10-01 06:42
Yes sure. I have assigned the issue to you

**Comment by AviSharma1305** [comment] 2020-10-01 18:52
I'd like to write the code for multiplying 2 numbers without using ( * ) operator.

**Comment by distroinfinity** [comment] 2020-10-07 17:45
I see the issue is still open, I can write the code. Please let me know in which directory to place the cpp file @amritansh22

**Comment by amritansh22** [comment] 2020-10-08 03:16
Yes sure you may take it @distroinfinity

**Comment by Deepak2417** [comment] 2020-10-12 10:22
I am willing to work on this using C++. Kindly assign this to me also.

**Comment by amritansh22** [comment] 2020-10-12 10:25
@Deepak2417 Yes sure. Open a PR once done

**Comment by prabhat34** [comment] 2020-10-16 11:37
i want to contribute , could you pls assign it to me?

**Comment by prabhat34** [comment] 2020-10-16 11:44
I am willing to do this issue , could you pls assign it to me?

**Closed** 2020-10-16 13:29 UTC
Labels: Hacktoberfest, Hacktoberfest2020, good first issue
